# image will be published to ghcr.io/<user>/<name>
name: heartsbane
# description will be included in the image's metadata
description: a simple silverblue image for Asus Strix Scar 15 2021

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-asus-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # - type: akmods
  #   base: asus
  #   install:
  #     - nvidia

  - type: gnome-extensions
    install:
      - 7065  # Tiling Shell
    # uninstall:
    #   - GSConnect

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/robot/veracrypt/repo/fedora-%OS_VERSION%/robot-veracrypt-fedora-%OS_VERSION%.repo
    remove:
      - toolbox
      - firefox
      - firefox-langpacks
    install:
      # DE Tools
      - gnome-shell-extension-system-monitor
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - ulauncher
      # Terminal tools
      - zoxide
      - stow
      - git
      - zsh
      - fastfetch
      # Entertainment tools
      # - vlc
      # - smplayer
      # printer / scanner utils
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - printer-driver-brlaser
      - simple-scan
      - foo2zjs
      - hplip
      # utilities
      - p7zip
      - p7zip-plugins
      - wl-clipboard
      - wireguard-tools
      - veracrypt
      - lm_sensors
      - openssh-askpass
      - udica
      - krb5-workstation
      - libxcrypt-compat
      - bcache-tools
      - bootc
      # Development
      - code
      - make
      - python3-pip
      - libxcrypt-compat
      - distrobox

  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - md.obsidian.Obsidian
        - io.gitlab.librewolf-community
        - com.mattjakeman.ExtensionManager
        - com.vivaldi.Vivaldi
        - org.wezfurlong.wezterm
        - io.podman_desktop.PodmanDesktop
        - com.transmissionbt.Transmission
        - info.smplayer.SMPlayer
        - org.videolan.VLC
        - com.github.liferooter.textpieces
        - com.nextcloud.desktopclient.nextcloud
        - com.github.tchx84.Flatseal
        - com.github.micahflee.torbrowser-launcher
        - com.bitwarden.desktop
        - io.dbeaver.DBeaverCommunity
        - org.gnome.meld
        - io.github.sigmasd.stimulator
        - com.brave.Browser
        - net.sapples.LiveCaptions
        - com.github.jeromerobert.pdfarranger
        - io.github.flattool.Warehouse
        - io.github.dvlv.boxbuddyrs
        - org.mozilla.firefox
        - com.github.hluk.copyq
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: script
    snippets:
      # - "curl https://example.com/examplebinary > /usr/bin/examplebinary" # example: download binary
      # - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld" # example: ld alternatives symlink workaround
    scripts:
      - optimizations.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - 0xProto
        - Agave
        - FiraMono
        - Iosevka
        - IosevkaTerm
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - OpenDyslexic
        # - SauceCodePro
      google-fonts:
        - Roboto
        - Open Sans
        - Lato

  - type: chezmoi
    repository: "https://github.com/muralidharanram/dotfiles"
    all-users: true # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo

  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - podman.socket

  - type: signing # this sets up the proper policy & signing files for signed images to work fully